name: Test

on: [push]

jobs:

  cache-precommit:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
      fail-fast: false
    steps:
    - uses: actions/checkout@v3.0.0
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v10
      with:
        name: earnestresearch-public
        signingKey: '${{ secrets.EARNESTRESEARCH_PUBLIC_CACHIX_SIGNING_KEY }}'
    - run: cachix use pre-commit-hooks
    - run: nix-env -i coreutils -f '<nixpkgs>'
    - run: timeout -v -k 1m 340m nix-build -E "(import ./.).pkgs.pre-commit-hooks"

  cache-haskell-nix-roots:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        ghc: [ ghc865, ghc884, ghc8104 ]
        pkgs: [ pkgs ]
      fail-fast: false
    steps:
    - uses: actions/checkout@v3.0.0
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v10
      with:
        name: earnestresearch-public
        signingKey: '${{ secrets.EARNESTRESEARCH_PUBLIC_CACHIX_SIGNING_KEY }}'
    - run: nix-env -i coreutils -f '<nixpkgs>'
    - run: timeout -v -k 1m 340m nix-build -E '(import ./.).${{ matrix.pkgs }}.haskell-nix.roots "${{ matrix.ghc }}"'

  cache-projects:
    needs: cache-haskell-nix-roots
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        ghc: [ ghc865, ghc884, ghc8104 ]
        buildMusl: [ false ]
      fail-fast: false
    steps:
    - uses: actions/checkout@v3.0.0
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v10
      with:
        name: earnestresearch-public
        signingKey: '${{ secrets.EARNESTRESEARCH_PUBLIC_CACHIX_SIGNING_KEY }}'
    - run: nix-env -i coreutils -f '<nixpkgs>'
    - run: cd test && timeout -v -k 1m 340m nix-shell --run "exit 0" --arg buildMusl '${{ matrix.buildMusl }}' --argstr compiler-nix-name '${{ matrix.ghc }}'

  cache-hls:
    needs: cache-haskell-nix-roots
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        ghc: [ ghc865, ghc884, ghc8104 ]
      fail-fast: false
    steps:
    - uses: actions/checkout@v3.0.0
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v10
      with:
        name: earnestresearch-public
        signingKey: '${{ secrets.EARNESTRESEARCH_PUBLIC_CACHIX_SIGNING_KEY }}'
    - run: nix-env -i coreutils -f '<nixpkgs>'
    - run: timeout -v -k 1m 340m nix-build -E "(import ./.).tools.haskellLanguageServersFor [ \"${{ matrix.ghc }}\" ]"
