name: Test

on: [push]

jobs:
  tests:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        ghc: [ ghc865, ghc883 ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - uses: cachix/install-nix-action@releases/v9
      with:
        skip_adding_nixpkgs_channel: true
    - uses: cachix/cachix-action@v6
      with:
        name: earnestresearch-public
        signingKey: '${{ secrets.EARNESTRESEARCH_PUBLIC_CACHIX_SIGNING_KEY }}'
        nixBuildArgs: --argstr ghc ${{ matrix.ghc }}
    - run: nix-build ci.nix
