name: Test

on: [push]

jobs:

  cache-precommit:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v11
      with:
        skip_adding_nixpkgs_channel: true
    - uses: cachix/cachix-action@v6
      with:
        name: earnestresearch-public
        signingKey: '${{ secrets.EARNESTRESEARCH_PUBLIC_CACHIX_SIGNING_KEY }}'
    - run: cachix use pre-commit-hooks
    - run: nix-build -E "(import ./.).pkgs.pre-commit-hooks"

  cache-linux-haskell-nix-roots:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pkgs: [ pkgs, pkgs.pkgsCross.musl64 ]
        ghc: [ ghc865, ghc883, ghc884, ghc8101 ]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v11
      with:
        skip_adding_nixpkgs_channel: true
    - uses: cachix/cachix-action@v6
      with:
        name: earnestresearch-public
        signingKey: '${{ secrets.EARNESTRESEARCH_PUBLIC_CACHIX_SIGNING_KEY }}'
    - run: nix-build -E '(import ./.).${{ matrix.pkgs }}.haskell-nix.roots "${{ matrix.ghc }}"'

  cache-macos-haskell-nix-roots:
    runs-on: macos-latest
    strategy:
      matrix:
        pkgs: [ pkgs ]
        ghc: [ ghc865, ghc883, ghc884, ghc8101 ]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v11
      with:
        skip_adding_nixpkgs_channel: true
    - uses: cachix/cachix-action@v6
      with:
        name: earnestresearch-public
        signingKey: '${{ secrets.EARNESTRESEARCH_PUBLIC_CACHIX_SIGNING_KEY }}'
    - run: nix-build -E '(import ./.).${{ matrix.pkgs }}.haskell-nix.roots "${{ matrix.ghc }}"'

  cache-linux-ghc:
    needs: cache-linux-haskell-nix-roots
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: [ ghc865, ghc883, ghc884, ghc8101 ]
        pkgs: [ pkgs, pkgs.pkgsCross.musl64 ]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v11
      with:
        skip_adding_nixpkgs_channel: true
    - uses: cachix/cachix-action@v6
      with:
        name: earnestresearch-public
        signingKey: '${{ secrets.EARNESTRESEARCH_PUBLIC_CACHIX_SIGNING_KEY }}'
    - run: nix-build -E "(import ./.).${{ matrix.pkgs }}.buildPackages.haskell-nix.compiler.${{ matrix.ghc }}"

  cache-macos-ghc:
    needs: cache-macos-haskell-nix-roots
    runs-on: macos-latest
    strategy:
      matrix:
        ghc: [ ghc865, ghc883, ghc884, ghc8101 ]
        pkgs: [ pkgs ]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v11
      with:
        skip_adding_nixpkgs_channel: true
    - uses: cachix/cachix-action@v6
      with:
        name: earnestresearch-public
        signingKey: '${{ secrets.EARNESTRESEARCH_PUBLIC_CACHIX_SIGNING_KEY }}'
    - run: nix-build -E "(import ./.).${{ matrix.pkgs }}.buildPackages.haskell-nix.compiler.${{ matrix.ghc }}"

  cache-linux-projects:
    needs: cache-linux-ghc
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: [ ghc865, ghc883, ghc884 ]
        buildMusl: [ true, false ]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v11
      with:
        skip_adding_nixpkgs_channel: true
    - uses: cachix/cachix-action@v6
      with:
        name: earnestresearch-public
        signingKey: '${{ secrets.EARNESTRESEARCH_PUBLIC_CACHIX_SIGNING_KEY }}'
    - run: cd test && nix-shell --run "exit 0" --arg buildMusl '${{ matrix.buildMusl }}' --argstr compiler-nix-name '${{ matrix.ghc }}'

  cache-macos-projects:
    needs: cache-macos-ghc
    runs-on: macos-latest
    strategy:
      matrix:
        ghc: [ ghc865, ghc883, ghc884 ]
        buildMusl: [ false ]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v11
      with:
        skip_adding_nixpkgs_channel: true
    - uses: cachix/cachix-action@v6
      with:
        name: earnestresearch-public
        signingKey: '${{ secrets.EARNESTRESEARCH_PUBLIC_CACHIX_SIGNING_KEY }}'
    - run: cd test && nix-shell --run "exit 0" --arg buildMusl '${{ matrix.buildMusl }}' --argstr compiler-nix-name '${{ matrix.ghc }}'
