name: Upgrade Niv and LTS

on:
  schedule:
    - cron: '0 8 9,24 * *'
  workflow_dispatch:
jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
      with:
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - uses: cachix/install-nix-action@v13
    - uses: cachix/cachix-action@v10
      with:
        name: earnestresearch-public
    - name: Update dependencies
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: GITHUB_PATH= nix-shell --command 'niv update'
    - name: Update test cabal.project.freeze to latest LTS
      run: curl -L https://www.stackage.org/lts/cabal.config > test/cabal.project.freeze
    - name: Create pull request
      id: cpr
      uses: peter-evans/create-pull-request@v4.0.1
      with:
        commit-message: Niv and LTS upgrades
        author: er-nix-bot <noreply@earnestresearch.com>
        branch: create-pull-request/upgrade
        delete-branch: true
        title: Niv and LTS upgrades
